name: Staging release pipeline

on:
  push:
    branches:
      - develop

jobs:
  sync_staging:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write

    environment:
      name: staging
      url: https://uikit.staging.amity.co/

    env:
      NPM_FONT_AWESOME_TOKEN: ${{ secrets.NPM_FONT_AWESOME_TOKEN }}
      STORYBOOK_API_REGION: ${{ secrets.STORYBOOK_API_REGION }}
      STORYBOOK_API_KEY: ${{ secrets.STORYBOOK_API_KEY }}
      STORYBOOK_USERS: ${{ secrets.STORYBOOK_USERS }}

    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path | tr -d '\n')" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: build storybook
        run: pnpm run storybook:build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sync to S3
        env:
          AWS_S3_BUCKET: uikit.staging.amity.co
          SOURCE_DIR: storybook-build
        run: |
          aws s3 sync ./$SOURCE_DIR s3://$AWS_S3_BUCKET --acl public-read --follow-symlinks --delete
