name: Dev release teardown

on:
  pull_request:
    types: [closed]

jobs:
  env_teardown:
    name: Teardown
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Remove S3 files
        env:
          AWS_S3_BUCKET: uikit.dev.amity.co
        run: |
          aws s3 rm s3://$AWS_S3_BUCKET/${{ github.event.pull_request.number }} --recursive
