name: Dev release teardown

on:
  pull_request:
    types: [closed]

jobs:
  env_teardown:
    name: Teardown
    runs-on: ubuntu-latest
    steps:
      - uses: vitorsgomes/s3-rm-action@master
        with:
          args: --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ui-kit-open-source.dev.amity.co
          PATH_TO_DELETE: ${{ github.event.pull_request.number }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Remove S3 files
        env:
          AWS_S3_BUCKET: uikit.dev.amity.co
        run: |
          aws s3 rm s3://$AWS_S3_BUCKET/${{ github.event.pull_request.number }} --recursive
